"""init

Revision ID: init
Revises:
Create Date: 2026-07-23 14:24:33.403619

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "init"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("password", sa.String(length=120), nullable=False),
        sa.Column("encrypted_recovery_key", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("name", name=op.f("uq_users_name")),
    )
    op.create_table(
        "agents",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("secret", sa.String(length=255), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=True),
        sa.Column("ssh_public_key", sa.Text(), nullable=True),
        sa.Column("ssh_key_fingerprint", sa.String(length=255), nullable=True),
        sa.Column("ssh_key_algorithm", sa.String(length=64), nullable=True),
        sa.Column("os", sa.String(length=255), nullable=True),
        sa.Column("version", sa.String(length=255), nullable=True),
        sa.Column("install_type", sa.String(length=32), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("last_connection", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_agents_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
    )
    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agents_user_id"), ["user_id"], unique=False)

    op.create_table(
        "notification_configs",
        sa.Column("encrypted_url", sa.JSON(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("operation_types", sa.JSON(), nullable=False),
        sa.Column("operation_states", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_configs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_configs")),
    )
    with op.batch_alter_table("notification_configs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_configs_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "retentions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("keep_last", sa.Integer(), nullable=True),
        sa.Column("keep_hourly", sa.Integer(), nullable=True),
        sa.Column("keep_weekly", sa.Integer(), nullable=True),
        sa.Column("keep_monthly", sa.Integer(), nullable=True),
        sa.Column("keep_yearly", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_retentions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retentions")),
        sa.UniqueConstraint("user_id", "name", name="uq_retentions_user_id_name"),
    )
    op.create_table(
        "user_secrets",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("encrypted_value", sa.JSON(), nullable=False),
        sa.Column("public_data", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_secrets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_secrets")),
        sa.UniqueConstraint("user_id", "type", "name", name="uq_user_secrets_user_id_type_name"),
    )
    op.create_table(
        "user_sessions",
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("public_id", name=op.f("uq_user_sessions_public_id")),
    )
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "agent_secret_envelopes",
        sa.Column("user_secret_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("encrypted_value", sa.JSON(), nullable=False),
        sa.Column("secret_version", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_agent_secret_envelopes_agent_id_agents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_secret_id"],
            ["user_secrets.id"],
            name=op.f("fk_agent_secret_envelopes_user_secret_id_user_secrets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_secret_envelopes")),
        sa.UniqueConstraint(
            "user_secret_id", "agent_id", name="uq_agent_secret_envelopes_secret_id_agent_id"
        ),
    )
    op.create_table(
        "agent_sessions",
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("request_sid", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_agent_sessions_agent_id_agents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_sessions")),
        sa.UniqueConstraint("agent_id", name=op.f("uq_agent_sessions_agent_id")),
        sa.UniqueConstraint("request_sid", name=op.f("uq_agent_sessions_request_sid")),
    )
    op.create_table(
        "jobs",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("file", "proxmox", name="agentjobtype", native_enum=False, length=255),
            nullable=False,
        ),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_jobs_agent_id_agents"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("uuid", name=op.f("uq_jobs_uuid")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_agent_id"), ["agent_id"], unique=False)

    op.create_table(
        "repositories",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=False),
        sa.Column("password_secret_id", sa.Integer(), nullable=True),
        sa.Column("restic_id", sa.String(length=255), nullable=True),
        sa.Column("encrypted_environment", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["password_secret_id"],
            ["user_secrets.id"],
            name=op.f("fk_repositories_password_secret_id_user_secrets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_repositories_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
        sa.UniqueConstraint("user_id", "name", name="uq_repositories_user_id_name"),
    )
    op.create_table(
        "agent_repositories",
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("encrypted_restic_access_key", sa.JSON(), nullable=True),
        sa.Column("restic_key_id", sa.String(length=255), nullable=True),
        sa.Column("provisioned", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_agent_repositories_agent_id_agents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_agent_repositories_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("agent_id", "repository_id", name=op.f("pk_agent_repositories")),
    )
    op.create_table(
        "job_actions",
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "module",
            sa.Enum(
                "command", "docker", name="agentjobactionmodule", native_enum=False, length=255
            ),
            nullable=False,
        ),
        sa.Column("hook", sa.String(length=255), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_actions_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_actions")),
    )
    with op.batch_alter_table("job_actions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_actions_job_id"), ["job_id"], unique=False)

    op.create_table(
        "job_schedules",
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("retention_id", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("advanced", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("cron_string", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_schedules_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_job_schedules_repository_id_repositories"),
        ),
        sa.ForeignKeyConstraint(
            ["retention_id"],
            ["retentions.id"],
            name=op.f("fk_job_schedules_retention_id_retentions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_schedules")),
    )
    with op.batch_alter_table("job_schedules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_schedules_job_id"), ["job_id"], unique=False)

    op.create_table(
        "agent_operations",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.Column("retention_id", sa.Integer(), nullable=True),
        sa.Column("parent_operation_id", sa.Integer(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "running",
                "warning",
                "failed",
                "success",
                "cancelled",
                name="agentoperationstate",
                native_enum=False,
                length=255,
            ),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum(
                "backup",
                "restore",
                "retention",
                "repository_check",
                "repository_unlock",
                "repository_stats",
                "sync",
                "command",
                name="agentoperationtype",
                native_enum=False,
                length=255,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "schedule",
                "triggered",
                "system",
                name="agentoperationsource",
                native_enum=False,
                length=255,
            ),
            nullable=False,
        ),
        sa.Column("started", sa.DateTime(), nullable=True),
        sa.Column("ended", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_agent_operations_agent_id_agents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_agent_operations_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_operation_id"],
            ["agent_operations.id"],
            name=op.f("fk_agent_operations_parent_operation_id_agent_operations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_agent_operations_repository_id_repositories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["retention_id"],
            ["retentions.id"],
            name=op.f("fk_agent_operations_retention_id_retentions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["job_schedules.id"],
            name=op.f("fk_agent_operations_schedule_id_job_schedules"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_operations")),
        sa.UniqueConstraint("uuid", name=op.f("uq_agent_operations_uuid")),
    )
    with op.batch_alter_table("agent_operations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_agent_operations_agent_started", ["agent_id", "started"], unique=False
        )
        batch_op.create_index(
            "ix_agent_operations_job_started", ["job_id", "started"], unique=False
        )

    op.create_table(
        "agent_operation_artifacts",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.Integer(), nullable=False),
        sa.Column("artifact_key", sa.String(length=255), nullable=False),
        sa.Column("snapshot_id", sa.String(length=255), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("forgotten_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["agent_operations.id"],
            name=op.f("fk_agent_operation_artifacts_operation_id_agent_operations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_operation_artifacts")),
        sa.UniqueConstraint(
            "operation_id", "artifact_key", name="uq_agent_operation_artifacts_operation_key"
        ),
        sa.UniqueConstraint("uuid", name=op.f("uq_agent_operation_artifacts_uuid")),
    )
    op.create_table(
        "agent_operation_logs",
        sa.Column("operation_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "info",
                "warning",
                "error",
                name="agentoperationloglevel",
                native_enum=False,
                length=255,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["agent_operations.id"],
            name=op.f("fk_agent_operation_logs_operation_id_agent_operations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_operation_logs")),
        sa.UniqueConstraint(
            "operation_id", "sequence", name="uq_agent_operation_logs_operation_sequence"
        ),
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("operation_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=255), nullable=False),
        sa.Column("notification_config_id", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_notification_deliveries_attempts_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["notification_config_id"],
            ["notification_configs.id"],
            name=op.f("fk_notification_deliveries_notification_config_id_notification_configs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["agent_operations.id"],
            name=op.f("fk_notification_deliveries_operation_id_agent_operations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
        sa.UniqueConstraint(
            "operation_id",
            "state",
            "notification_config_id",
            name="uq_notification_deliveries_operation_state_config",
        ),
    )
    with op.batch_alter_table("notification_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_notification_deliveries_open", ["sent_at", "created", "id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_deliveries")
    op.drop_table("agent_operation_logs")
    op.drop_table("agent_operation_artifacts")
    op.drop_table("agent_operations")
    op.drop_table("job_schedules")
    op.drop_table("job_actions")
    op.drop_table("agent_repositories")
    op.drop_table("repositories")
    op.drop_table("jobs")
    op.drop_table("agent_sessions")
    op.drop_table("agent_secret_envelopes")
    op.drop_table("user_sessions")
    op.drop_table("user_secrets")
    op.drop_table("retentions")
    op.drop_table("notification_configs")
    op.drop_table("agents")
    op.drop_table("users")
    # ### end Alembic commands ###
