name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  publish:
    name: Publish Release Notes
    runs-on: ubuntu-24.04
    steps:
      - uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
